### ISSUE TITLE
Big endian is not supported?

### ISSUE THREAD

**Issue by WandyLau** [gvanas/KeccakCodePackage#38]
Recently I tired this module in s390 which is a big endian platform.
And I found that big endian is not supported.

**Comment by gvanas** [comment]
Which target did you compile? As far as I can tell, the s390 is a 32-bit machine, so you could try with `make generic32/KeccakTests`. This implementation should support big endian platforms.

I wrote "should" because I don't have access to a big-endian 32-bit machine, so feel free to submit a fix if needed.

**Comment by WandyLau** [comment]
thanks for your reply. s390 is not a 32-bit machine. Nowadays, almost are 64 bits. And now we are using 64bits one.  So it is a 64-bites big endian machine.

Actually it is used in a python module, which is a dependency. When I try to install that module, error : 

`src/64/KeccakF-1600-opt64.c: In function 'KeccakF1600_StateOverwriteBytesInLane':
src/64/KeccakF-1600-opt64.c:201:2: error: #error "Not yet implemented"
 #error "Not yet implemented"
  ^
src/64/KeccakF-1600-opt64.c: In function 'KeccakF1600_StateOverwriteLanes':
src/64/KeccakF-1600-opt64.c:222:2: error: #error "Not yet implemented"
 #error "Not yet implemented"
  ^
src/64/KeccakF-1600-opt64.c: In function 'KeccakF1600_StateOverwriteWithZeroes':
src/64/KeccakF-1600-opt64.c:250:2: error: #error "Not yet implemented"
 #error "Not yet implemented"
`
As I can see all these errors resulting from big endian not supported.
So I just ask this.

There is another module which just walks around this big endian problem by making big endian to default setting as others. And I can use it on s390, but not sure if this is good.

From the comment, I can see 64-bits big endian is not supported.

**Comment by gvanas** [comment]
Ah, yes, I see. Big endian support was indeed missing there.

I just pushed a fix. Can you please check if it works on your side? To do so, do `make generic64/KeccakTests`, then run `bin/generic64/KeccakTests -p`.

Note: The fix does not work with lane complementing, i.e., with `generic64lc` instead of `generic64`.

**Comment by WandyLau** [comment]
Thanks very much for your work. I really appreciate it. I will patch the python module accordingly. 
I have no idea about what does this **lane complementing** means? Will this affect much?
Sorry, I am not so familiar with the back ground or the concepts. Would you please give me some
examples? some link will be OK.

**Comment by gvanas** [comment]
You are welcome.

Lane complementing is an optimization technique that reduces the number of "not" operations on machines that do not have a "and not" instruction (*). The fix that I pushed yesterday does not cover it when combined with big endianness.

Anyway, I just pushed a fix that removes this limitation. Please consider this latest version for your patch.

(*) For more information, please see Section 2.2 of the [Keccak implementation overview](https://keccak.team/files/Keccak-implementation-3.2.pdf).

**Comment by WandyLau** [comment]
OK thanks.
